server.port=8083
spring.application.name=appointment-service

# Database (Local Docker Compose Port)
spring.datasource.url=jdbc:postgresql://localhost:5434/medinsight_platform
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Kafka (Local Docker Compose Port)
spring.kafka.bootstrap-servers=localhost:9092

# Keycloak (Local Docker Compose Port)
keycloak.server-url=http://localhost:8180
keycloak.realm=microservices-realm
keycloak.client-id=appointment-service
keycloak.client-secret=appointment-service-secret-2024
