server.port=8083
spring.application.name=appointment-service

# Database (Postgres Service DNS in K8s)
spring.datasource.url=jdbc:postgresql://postgres:5432/medinsight_platform
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka (Kafka Service DNS in K8s)
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Resource server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8180/realms/microservices-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8180/realms/microservices-realm/protocol/openid-connect/certs

# Keycloak
keycloak.server-url=http://keycloak:8180
keycloak.realm=microservices-realm
keycloak.client-id=appointment-service
keycloak.client-secret=NqPxCJf4gAuCgEAsiJ2WMVukmHd1a5mb
