server.port=8080
spring.application.name=dossier-service

# Database (Local host talking to Docker Postgres on port 5434)
spring.datasource.url=jdbc:postgresql://postgres:5432/medinsight_platform

spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka (Local host talking to Docker Kafka on port 9092)
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Resource server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8180/realms/microservices-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8180/realms/microservices-realm/protocol/openid-connect/certs

# Keycloak Admin client (Local host talking to Keycloak on port 8180)
keycloak.server-url=http://keycloak:8180

keycloak.realm=microservices-realm
keycloak.client-id=dossier-service
keycloak.client-secret=dossier-service-secret-2024

# Jackson Date Formatting
spring.jackson.serialization.write-dates-as-timestamps=false